import { getToken, getUser, saveAuthData, clearAuthData, isLoggedIn } from "./apiClient";
import {
  authApi,
  getMerchantAllEventsApi,
  getMerchantEventsApi,
  getMerchantChatApi,
  sendMerchantMessageApi,
  activateReservationApi,
  cancelReservationApi,
  getServicesApi,
  getSubServicesApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  getMerchantProfileApi,
  updateProfileApi,
  updateMerchantProfileApi,
  getMerchantLocationsApi,
  addMerchantLocationApi,
  updateMerchantLocationApi,
  getMerchantCouponsApi,
  addMerchantCouponApi,
  updateMerchantCouponApi,
  deleteMerchantCouponApi,
  getAddressesApi,
  addAddressApi,
} from "./authApi";

export {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  authApi,
  getMerchantAllEventsApi,
  getMerchantEventsApi,
  getMerchantChatApi,
  sendMerchantMessageApi,
  activateReservationApi,
  cancelReservationApi,
  getServicesApi,
  getSubServicesApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  getMerchantProfileApi,
  updateProfileApi,
  updateMerchantProfileApi,
  getMerchantLocationsApi,
  addMerchantLocationApi,
  updateMerchantLocationApi,
  getMerchantCouponsApi,
  addMerchantCouponApi,
  updateMerchantCouponApi,
  deleteMerchantCouponApi,
  getAddressesApi,
  addAddressApi,
};

export const authService = {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  getMerchantAllEvents: getMerchantAllEventsApi,
  getMerchantEvents: getMerchantEventsApi,
  getMerchantChat: getMerchantChatApi,
  sendMerchantMessage: sendMerchantMessageApi,
  activateReservation: activateReservationApi,
  cancelReservation: cancelReservationApi,
  getServices: getServicesApi,
  getSubServices: getSubServicesApi,
  signup: signupApi,
  verifyOtp: verifyOtpApi,
  login: loginApi,
  logout: logoutApi,
  deleteUser: deleteUserApi,
  forgotPassword: forgotPasswordApi,
  resetPassword: resetPasswordApi,
  changePassword: changePasswordApi,
  getUserProfile: getUserProfileApi,
  getMerchantProfile: getMerchantProfileApi,
  updateProfile: updateProfileApi,
  updateMerchantProfile: updateMerchantProfileApi,
  getMerchantLocations: getMerchantLocationsApi,
  addMerchantLocation: addMerchantLocationApi,
  updateMerchantLocation: updateMerchantLocationApi,
  getMerchantCoupons: getMerchantCouponsApi,
  addMerchantCoupon: addMerchantCouponApi,
  updateMerchantCoupon: updateMerchantCouponApi,
  deleteMerchantCoupon: deleteMerchantCouponApi,
  getAddresses: getAddressesApi,
  addAddress: addAddressApi,
};

export default authApi;
