import { getToken, getUser, saveAuthData, clearAuthData, isLoggedIn } from "./apiClient";
import {
  authApi,
  getMerchantAllEventsApi,
  getMerchantEventsApi,
  getMerchantChatApi,
  sendMerchantMessageApi,
  activateReservationApi,
  cancelReservationApi,
  getServicesApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  updateProfileApi,
  getAddressesApi,
  addAddressApi,
} from "./authApi";

export {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  authApi,
  getMerchantAllEventsApi,
  getMerchantEventsApi,
  getMerchantChatApi,
  sendMerchantMessageApi,
  activateReservationApi,
  cancelReservationApi,
  getServicesApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  updateProfileApi,
  getAddressesApi,
  addAddressApi,
};

export const authService = {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  getMerchantAllEvents: getMerchantAllEventsApi,
  getMerchantEvents: getMerchantEventsApi,
  getMerchantChat: getMerchantChatApi,
  sendMerchantMessage: sendMerchantMessageApi,
  activateReservation: activateReservationApi,
  cancelReservation: cancelReservationApi,
  getServices: getServicesApi,
  signup: signupApi,
  verifyOtp: verifyOtpApi,
  login: loginApi,
  logout: logoutApi,
  deleteUser: deleteUserApi,
  forgotPassword: forgotPasswordApi,
  resetPassword: resetPasswordApi,
  changePassword: changePasswordApi,
  getUserProfile: getUserProfileApi,
  updateProfile: updateProfileApi,
  getAddresses: getAddressesApi,
  addAddress: addAddressApi,
};

export default authApi;
