export const countryCodes = [
  { code: "+91", country: "India", iso: "IN", flag: "🇮🇳" },
  { code: "+1", country: "United States", iso: "US", flag: "🇺🇸" },
  { code: "+1", country: "Canada", iso: "CA", flag: "🇨🇦" },
  { code: "+44", country: "United Kingdom", iso: "GB", flag: "🇬🇧" },
  { code: "+971", country: "United Arab Emirates", iso: "AE", flag: "🇦🇪" },
  { code: "+966", country: "Saudi Arabia", iso: "SA", flag: "🇸🇦" },
  { code: "+61", country: "Australia", iso: "AU", flag: "🇦🇺" },
  { code: "+49", country: "Germany", iso: "DE", flag: "🇩🇪" },
  { code: "+33", country: "France", iso: "FR", flag: "🇫🇷" },
  { code: "+81", country: "Japan", iso: "JP", flag: "🇯🇵" },
  { code: "+86", country: "China", iso: "CN", flag: "🇨🇳" },
  { code: "+65", country: "Singapore", iso: "SG", flag: "🇸🇬" },
  { code: "+60", country: "Malaysia", iso: "MY", flag: "🇲🇾" },
  { code: "+92", country: "Pakistan", iso: "PK", flag: "🇵🇰" },
  { code: "+880", country: "Bangladesh", iso: "BD", flag: "🇧🇩" },
  { code: "+94", country: "Sri Lanka", iso: "LK", flag: "🇱🇰" },
  { code: "+977", country: "Nepal", iso: "NP", flag: "🇳🇵" },
  { code: "+63", country: "Philippines", iso: "PH", flag: "🇵🇭" },
  { code: "+62", country: "Indonesia", iso: "ID", flag: "🇮🇩" },
  { code: "+82", country: "South Korea", iso: "KR", flag: "🇰🇷" },
  { code: "+39", country: "Italy", iso: "IT", flag: "🇮🇹" },
  { code: "+34", country: "Spain", iso: "ES", flag: "🇪🇸" },
  { code: "+31", country: "Netherlands", iso: "NL", flag: "🇳🇱" },
  { code: "+41", country: "Switzerland", iso: "CH", flag: "🇨🇭" },
  { code: "+46", country: "Sweden", iso: "SE", flag: "🇸🇪" },
  { code: "+47", country: "Norway", iso: "NO", flag: "🇳🇴" },
  { code: "+45", country: "Denmark", iso: "DK", flag: "🇩🇰" },
  { code: "+353", country: "Ireland", iso: "IE", flag: "🇮🇪" },
  { code: "+55", country: "Brazil", iso: "BR", flag: "🇧🇷" },
  { code: "+52", country: "Mexico", iso: "MX", flag: "🇲🇽" },
  { code: "+54", country: "Argentina", iso: "AR", flag: "🇦🇷" },
  { code: "+27", country: "South Africa", iso: "ZA", flag: "🇿🇦" },
  { code: "+20", country: "Egypt", iso: "EG", flag: "🇪🇬" },
  { code: "+234", country: "Nigeria", iso: "NG", flag: "🇳🇬" },
  { code: "+254", country: "Kenya", iso: "KE", flag: "🇰🇪" },
  { code: "+968", country: "Oman", iso: "OM", flag: "🇴🇲" },
  { code: "+974", country: "Qatar", iso: "QA", flag: "🇶🇦" },
  { code: "+965", country: "Kuwait", iso: "KW", flag: "🇰🇼" },
  { code: "+973", country: "Bahrain", iso: "BH", flag: "🇧🇭" },
  { code: "+964", country: "Iraq", iso: "IQ", flag: "🇮🇶" },
  { code: "+962", country: "Jordan", iso: "JO", flag: "🇯🇴" },
  { code: "+961", country: "Lebanon", iso: "LB", flag: "🇱🇧" },
  { code: "+90", country: "Turkey", iso: "TR", flag: "🇹🇷" },
  { code: "+64", country: "New Zealand", iso: "NZ", flag: "🇳🇿" },
  { code: "+7", country: "Russia", iso: "RU", flag: "🇷🇺" },
  { code: "+380", country: "Ukraine", iso: "UA", flag: "🇺🇦" },
  { code: "+48", country: "Poland", iso: "PL", flag: "🇵🇱" },
  { code: "+43", country: "Austria", iso: "AT", flag: "🇦🇹" },
  { code: "+32", country: "Belgium", iso: "BE", flag: "🇧🇪" },
  { code: "+351", country: "Portugal", iso: "PT", flag: "🇵🇹" },
  { code: "+30", country: "Greece", iso: "GR", flag: "🇬🇷" },
  { code: "+36", country: "Hungary", iso: "HU", flag: "🇭🇺" },
  { code: "+420", country: "Czech Republic", iso: "CZ", flag: "🇨🇿" },
  { code: "+66", country: "Thailand", iso: "TH", flag: "🇹🇭" },
  { code: "+84", country: "Vietnam", iso: "VN", flag: "🇻🇳" },
];
